#!/usr/bin/env bash
# Voice nav one-click start (term1=voice, 2=chassis, 3=MicroROS, 4=flask, 5=Nav2)
#
# Usage:
#   bash scripts/start_voice_nav_oneclick.sh
#   AI_CAR_SKIP_CHASSIS_PROMPT=1 bash scripts/start_voice_nav_oneclick.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=ai_car_common.sh
source "${SCRIPT_DIR}/ai_car_common.sh"
# shellcheck source=voice_nav_audio.sh
source "${SCRIPT_DIR}/voice_nav_audio.sh"
if [[ -f "${SCRIPT_DIR}/voice_nav_env.sh" ]]; then
  # shellcheck source=voice_nav_env.sh
  source "${SCRIPT_DIR}/voice_nav_env.sh"
elif [[ -f "${SCRIPT_DIR}/voice_nav_cloud.sh" ]]; then
  echo "[warn] voice_nav_env.sh missing, fallback voice_nav_cloud.sh"
  # shellcheck source=voice_nav_cloud.sh
  source "${SCRIPT_DIR}/voice_nav_cloud.sh"
  voice_nav_env_info() { voice_nav_cloud_info; }
else
  echo "[warn] voice_nav_env.sh missing, using inline defaults"
  export DASHSCOPE_API_KEY="${DASHSCOPE_API_KEY:-}"
  export DASHSCOPE_BASE_URL="${DASHSCOPE_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}"
  export DASHSCOPE_MODEL="${DASHSCOPE_MODEL:-qwen-max}"
  export VOICE_NAV_USE_LLM="${VOICE_NAV_USE_LLM:-1}"
  export VOICE_NAV_BACKEND="${VOICE_NAV_BACKEND:-auto}"
  export VOICE_NAV_CLOUD_TIMEOUT="${VOICE_NAV_CLOUD_TIMEOUT:-15}"
  export VOICE_NAV_CLOUD_MAX_TOKENS="${VOICE_NAV_CLOUD_MAX_TOKENS:-256}"
  export VOICE_NAV_STARTUP_JSON="${VOICE_NAV_STARTUP_JSON:-1}"
  export VOICE_NAV_TTS_STARTUP="${VOICE_NAV_TTS_STARTUP:-1}"
  export AI_CAR_LLM_HOST="${AI_CAR_LLM_HOST:-http://127.0.0.1:8001}"
  export AI_CAR_LLM_PATH="${AI_CAR_LLM_PATH:-/rkllm_chat}"
  export VOICE_NAV_LLM_TIMEOUT="${VOICE_NAV_LLM_TIMEOUT:-20}"
  export VOICE_NAV_MQTT_BROKER="${VOICE_NAV_MQTT_BROKER:-broker.emqx.io}"
  export VOICE_NAV_MQTT_TOPIC="${VOICE_NAV_MQTT_TOPIC:-robot/nav_room}"
  export VOICE_NAV_ROBOT_ID="${VOICE_NAV_ROBOT_ID:-robot01}"
  voice_nav_env_info() {
    echo "  LLM:      VOICE_NAV_USE_LLM=${VOICE_NAV_USE_LLM} backend=${VOICE_NAV_BACKEND}"
    echo "  Cloud:    ${DASHSCOPE_MODEL} @ ${DASHSCOPE_BASE_URL}"
    echo "  Local:    ${AI_CAR_LLM_HOST}${AI_CAR_LLM_PATH}"
    echo "  MQTT nav: ${VOICE_NAV_MQTT_BROKER} topic=${VOICE_NAV_MQTT_TOPIC}"
    if [[ -z "${DASHSCOPE_API_KEY:-}" ]]; then
      echo "  [warn] DASHSCOPE_API_KEY not set"
    fi
  }
fi

AI_CAR_ROS_WS="$(ai_car_resolve_ros_ws "${SCRIPT_DIR}")"
export AI_CAR_ROS_WS
MICROROS_WS="${AI_CAR_MICROROS_WS:-${HOME}/Desktop/rock_ws/microros_ws}"
RKSDK="${AI_CAR_RKSDK:-${HOME}/Desktop/ai_app/RKSDK}"
LLM_DIR="${AI_CAR_LLM_DIR:-${RKSDK}/test_rkllm_run}"
SHERPA_VENV="${SHERPA_VENV:-${HOME}/Desktop/rk3588-offline-bundle/venv/bin/activate}"

RUNTIME_ENV="${AI_CAR_ROS_WS}/.voice_nav_runtime.env"
{
  echo "# auto-generated by start_voice_nav_oneclick.sh"
  echo "export AI_CAR_ROS_WS='${AI_CAR_ROS_WS}'"
  echo "export DASHSCOPE_API_KEY='${DASHSCOPE_API_KEY}'"
  echo "export DASHSCOPE_BASE_URL='${DASHSCOPE_BASE_URL}'"
  echo "export DASHSCOPE_MODEL='${DASHSCOPE_MODEL}'"
  echo "export VOICE_NAV_USE_LLM='${VOICE_NAV_USE_LLM}'"
  echo "export VOICE_NAV_BACKEND='${VOICE_NAV_BACKEND}'"
  echo "export VOICE_NAV_CLOUD_TIMEOUT='${VOICE_NAV_CLOUD_TIMEOUT}'"
  echo "export VOICE_NAV_CLOUD_MAX_TOKENS='${VOICE_NAV_CLOUD_MAX_TOKENS}'"
  echo "export AI_CAR_LLM_HOST='${AI_CAR_LLM_HOST}'"
  echo "export AI_CAR_LLM_PATH='${AI_CAR_LLM_PATH}'"
  echo "export VOICE_NAV_LLM_TIMEOUT='${VOICE_NAV_LLM_TIMEOUT}'"
  echo "export CAR_CMD='${CAR_CMD:-${AI_CAR_ROS_WS}/car_cmd.sh}'"
} > "${RUNTIME_ENV}"

_env_prefix() {
  printf "source '%s'; " "${RUNTIME_ENV}"
}

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

export DISPLAY="${DISPLAY:-:0}"
export CAR_CMD="${CAR_CMD:-${AI_CAR_ROS_WS}/car_cmd.sh}"
export CAR_CMD_PYTHON="${CAR_CMD_PYTHON:-/usr/bin/python3}"

clear
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Voice Nav One-Click Start${NC}"
echo -e "${GREEN}========================================${NC}"
voice_nav_env_info
echo -e "${CYAN}  term1=voice  term2=chassis  term3=MicroROS  term4=flask  term5=Nav2${NC}"
echo ""

bash "${SCRIPT_DIR}/install_voice_nav.sh" 2>/dev/null || true

ai_car_start_stack "${SCRIPT_DIR}" "${MICROROS_WS}" "${AI_CAR_ROS_WS}" "${RKSDK}" "${LLM_DIR}"

echo ""
echo -e "${YELLOW}==== [5] term5 Nav2 + smart_switcher (aligned with start_multi_map) ====${NC}"
export VOICE_NAV_USE_DEPTH_NAV="${VOICE_NAV_USE_DEPTH_NAV:-0}"
export VOICE_NAV_AUTO_INITIALPOSE="${VOICE_NAV_AUTO_INITIALPOSE:-0}"
export VOICE_NAV_OPEN_RVIZ="${VOICE_NAV_OPEN_RVIZ:-false}"

if pgrep -f "smart_switcher" >/dev/null 2>&1; then
  echo "  smart_switcher already running"
else
  ai_car_stop_prewarm_sensor_launches
  ai_car_open_terminal "term5-nav" \
    "$(ai_car_nav_terminal_preamble "${SCRIPT_DIR}") \
     $(ai_car_voice_nav_stack_env) \
     $(_env_prefix) export AI_CAR_ROS_WS='${AI_CAR_ROS_WS}'; \
     bash '${SCRIPT_DIR}/ai_car_nav_term.sh'"
  sleep 2
fi

echo ""
echo -e "${YELLOW}==== [6] wait Nav2 ready (~10s) before voice ====${NC}"
ai_car_wait_nav_stack_ready || true

ai_car_source_ros
if [[ -f "${CAR_CMD}" ]]; then
  bash "${CAR_CMD}" warmup 2>/dev/null || true
fi

if [[ ! -f "${SHERPA_VENV}" ]]; then
  echo "[error] Sherpa venv not found: ${SHERPA_VENV}"
  exit 1
fi

# shellcheck source=/dev/null
source "${SHERPA_VENV}"

echo ""
echo -e "${YELLOW}==== TTS setup (Sherpa Matcha + 3.5mm) ====${NC}"
voice_nav_setup_playback

echo ""
echo -e "${YELLOW}==== startup probe (cloud key / network / local) ====${NC}"
if ! ai_car_voice_nav_startup_probe "${AI_CAR_ROS_WS}"; then
  echo "[error] LLM not ready (check cloud API key / network or start local flask)"
  exit 1
fi

AUDIO_DEV="$(ai_car_detect_astra_device_or_die)"

echo ""
echo -e "${GREEN}==== term1 voice nav (speak now) ====${NC}"
echo -e "${CYAN}mic: ${AUDIO_DEV}${NC}"
echo -e "${CYAN}try: finance where | I am hungry | go to 201 | yes${NC}"
echo ""

ai_car_run_stt "${AUDIO_DEV}" "${SCRIPT_DIR}/voice_to_nav_agent.py"
